import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { createServer } from '../apps/server/src/app.ts';
import { publish, managedPath } from '../apps/server/src/storage.ts';
import { discoverTools, probe, runProcess, validateMedia } from '../packages/media/src/index.ts';

const evidence=path.resolve('test-output/clip-edit');
await mkdir(evidence,{recursive:true});
const tools=await discoverTools(),fixture=path.join(evidence,'source.mp4'),clipFile=path.join(evidence,'clip.mp4');
await runProcess(tools.ffmpeg,['-y','-v','error','-f','lavfi','-i','testsrc2=size=640x360:rate=10:duration=4','-c:v','libx264',fixture]);
await runProcess(tools.ffmpeg,['-y','-v','error','-ss','1','-i',fixture,'-t','1.5','-c:v','libx264',clipFile]);
const clipHash=createHash('sha256').update(await readFile(clipFile)).digest('hex');
const token=randomUUID(),app=await createServer({dataDir:path.join(evidence,`service-${Date.now()}`),ownerToken:token,tools,encoders:[]});
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const owner=app.store.users().find(user=>user.role==='owner')!;
  const clip=await publish(app.store,clipFile,owner.id,'Saved clip.mp4',await probe(clipFile,tools),'export');
  const url='/api/v1/sources/from-artifact',headers={host:'localhost',authorization:`Bearer ${token}`};
  const member=app.store.createUser('Other user','member'),memberToken=app.store.token(member.id,'Other').token;
  assert.equal((await app.inject({method:'POST',url,headers:{...headers,authorization:`Bearer ${memberToken}`},payload:{artifactId:clip.id}})).statusCode,404);
  const readToken=app.store.token(owner.id,'Read',['read']).token;
  assert.equal((await app.inject({method:'POST',url,headers:{...headers,authorization:`Bearer ${readToken}`},payload:{artifactId:clip.id}})).statusCode,403);
  await app.listen({host:'127.0.0.1',port:0});
  const address=app.server.address();assert(address&&typeof address==='object');
  const origin=`http://127.0.0.1:${address.port}`;
  const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(30000);
  await page.request.post(`${origin}/api/v1/session`,{headers:{origin},data:{token}});
  await page.goto(origin);await page.getByRole('button',{name:'Library',exact:true}).click();
  await page.getByRole('button',{name:'Edit clip',exact:true}).click();
  await page.getByRole('heading',{name:'Editor · Saved clip.mp4'}).waitFor();
  await page.waitForFunction(()=>document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')?.readyState!>=2);
  const editable=app.store.all<any>('source',owner.id).find(source=>source.artifactId===clip.id);assert(editable);
  const repeated=await app.inject({method:'POST',url,headers,payload:{artifactId:clip.id}});assert.equal(repeated.statusCode,200);assert.equal(repeated.json().id,editable.id);
  assert.equal(Number(await page.getByRole('slider',{name:'Section end',exact:true}).inputValue()),1.5);
  const start=page.getByLabel('Region 1 in timecode',{exact:true}),end=page.getByLabel('Region 1 out timecode',{exact:true});
  await start.fill('.2');await start.press('Enter');
  await end.fill('1.2');await end.press('Enter');
  assert.equal(await start.inputValue(),'00:00:00.200');assert.equal(await end.inputValue(),'00:00:01.200');
  await page.getByRole('button',{name:'Go to section start',exact:true}).click();
  await page.waitForFunction(()=>Math.abs(document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')!.currentTime-.2)<.01);
  const sourcePlayhead=page.getByLabel('Timeline playhead',{exact:true});
  await sourcePlayhead.evaluate((element:HTMLInputElement)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(element,'.5');element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));});
  await page.waitForFunction(()=>Math.abs(document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')!.currentTime-.5)<.01);
  await page.getByRole('button',{name:'Set start I',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('input[aria-label="Region 1 in timecode"]')?.value==='00:00:00.500');
  await page.getByRole('slider',{name:'Section start',exact:true}).focus();
  await page.getByRole('slider',{name:'Section start',exact:true}).press('ArrowRight');
  assert.equal(await start.inputValue(),'00:00:00.501');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('input[aria-label="Region 1 in timecode"]')?.value==='00:00:00.500');
  const handle=page.getByRole('slider',{name:'Region 1 end trim handle',exact:true}),bounds=await handle.boundingBox();assert(bounds);
  await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.mouse.move(bounds.x-65,bounds.y+bounds.height/2,{steps:5});await page.mouse.up();
  assert(Number(await page.getByRole('slider',{name:'Section end',exact:true}).inputValue())<1.2);
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('input[aria-label="Region 1 out timecode"]')?.value==='00:00:01.200');
  await sourcePlayhead.evaluate((element:HTMLInputElement)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(element,'1.3');element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));});
  await page.waitForFunction(()=>Math.abs(document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')!.currentTime-1.3)<.01);
  await page.getByRole('button',{name:'+ New region',exact:true}).click();
  await page.getByRole('button',{name:'Select region 1',exact:true}).click();
  await page.waitForFunction(()=>Math.abs(document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')!.currentTime-.5)<.01);
  await page.getByRole('button',{name:'Select region 2',exact:true}).click();
  assert.equal(await page.getByLabel('Region 2 in timecode',{exact:true}).inputValue(),'00:00:01.300');
  await page.waitForFunction(()=>Math.abs(document.querySelector<HTMLVideoElement>('video[aria-label="Source playback"]')!.currentTime-1.3)<.01);
  await page.screenshot({path:path.join(evidence,'trim-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('navigation',{name:'Editing tools'}).getByRole('button',{name:'Cut',exact:true}).click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(evidence,'trim-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.getByLabel('Cutting mode',{exact:true}).selectOption('auto');
  const previewStarted=performance.now();
  await page.getByRole('button',{name:'Render edited preview',exact:true}).click();
  await page.getByLabel('Rendered export preview',{exact:true}).waitFor();
  const previewMs=performance.now()-previewStarted;
  const job=app.store.jobs(owner.id).find(j=>j.request.type==='export');assert(job);
  assert.equal(job.state,'completed',job.error);assert.equal(job.plan?.strategy,'copy');
  assert.match(String(job.plan?.validation),/bounded cut-edge/);
  const output=await validateMedia(await managedPath(app.store,job.artifactId!),tools);assert(output.duration>0);
  await page.getByRole('dialog',{name:'Export preview',exact:true}).screenshot({path:path.join(evidence,'fast-cut-preview.png')});
  await page.getByRole('button',{name:'Close preview',exact:true}).click();
  // Debounced drafts still flush on immediate navigation and restore cut/export choices.
  await page.getByLabel('Cutting mode',{exact:true}).selectOption('exact');
  await page.getByRole('button',{name:'Library',exact:true}).click();
  await page.getByRole('button',{name:'Editor',exact:true}).click();
  assert.equal(await page.getByLabel('Cutting mode',{exact:true}).inputValue(),'exact');
  assert.equal(createHash('sha256').update(await readFile(await managedPath(app.store,clip.id))).digest('hex'),clipHash);
  assert.equal(await page.getByRole('alert').count(),0);
  console.log(`Passed: exported clip editing, ownership/scope, source reuse, precise bounds, playhead buttons, slider, drag, undo, section selection, mobile layout, unchanged clip bytes, fast lossless preview in ${Math.round(previewMs)} ms, draft flush on navigation.`);
}finally{await browser.close();await app.close();}
