import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { access, copyFile, mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { createServer } from '../apps/server/src/app.ts';
import { managedPath, publish, registerSource } from '../apps/server/src/storage.ts';
import { discoverTools, probe, runProcess } from '../packages/media/src/index.ts';
import { JobRequestSchema } from '../packages/contracts/src/index.ts';
import type { Artifact } from '../packages/contracts/src/index.ts';

const evidence=path.resolve('test-output/library');
await mkdir(evidence,{recursive:true});
const tools=await discoverTools(),fixture=path.join(evidence,'fixture.mkv');
await runProcess(tools.ffmpeg,['-y','-v','error','-f','lavfi','-i','testsrc2=size=640x360:rate=10:duration=2','-c:v','libx264',fixture]);
const token=randomUUID(),app=await createServer({dataDir:path.join(evidence,`service-${Date.now()}`),ownerToken:token,tools,encoders:[],startQueue:false});
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
  const owner=app.store.users().find(user=>user.role==='owner')!;
  const media=await probe(fixture,tools);
  const seeded:Artifact[]=[];
  for(const [index,kind] of (['original','download','export','proxy'] as Artifact['kind'][]).entries()){
    const staged=path.join(evidence,`staged-${index}.mkv`);await copyFile(fixture,staged);
    const artifact=await publish(app.store,staged,owner.id,`${kind} video.mkv`,media,kind);
    // Deliberately insert out of date order, including equivalent-offset timestamps.
    artifact.createdAt=['2026-01-02T08:00:00Z','2026-01-04T08:00:00Z','2026-01-03T13:00:00+03:00','2026-01-03T11:00:00Z'][index];
    app.store.put('artifact',artifact.id,owner.id,artifact);seeded.push(artifact);
    if(kind==='original')registerSource(app.store,artifact);
    const url=`/api/v1/artifacts/${artifact.id}/thumbnail`;
    const response=await app.inject({url,headers:{host:'localhost',authorization:`Bearer ${token}`}});
    assert.equal(response.statusCode,200,response.body);
    assert.match(response.headers['content-type'] as string,/image\/jpeg/);
    assert.equal(response.rawPayload.readUInt16BE(0),0xffd8);
    const guest=app.store.createUser(`Guest ${index}`,'restricted-guest');
    const guestToken=app.store.token(guest.id,'Guest').token;
    assert.equal((await app.inject({url,headers:{host:'localhost',authorization:`Bearer ${guestToken}`}})).statusCode,404);
    assert.equal((await app.inject({url,headers:{host:'localhost'}})).statusCode,401);
  }
  await app.listen({host:'127.0.0.1',port:0});
  const address=app.server.address();assert(address&&typeof address==='object');
  const origin=`http://127.0.0.1:${address.port}`;

  const originalSource=app.store.all<any>('source',owner.id).find(s=>s.artifactId===seeded[0].id);
  const download=app.store.submit(owner.id,JobRequestSchema.parse({type:'download',download:{url:'https://example.com/coast.mp4'}}),randomUUID()).job;
  app.store.updateJob(download.id,{state:'downloading',progress:.42});
  const failure=app.store.submit(owner.id,JobRequestSchema.parse({type:'download',download:{url:'https://example.com/unavailable.mp4'}}),randomUUID()).job;
  app.store.updateJob(failure.id,{state:'failed',error:'This video is unavailable. Check the link and retry.'});
  const queued=app.store.submit(owner.id,JobRequestSchema.parse({type:'proxy',sourceId:originalSource.id}),randomUUID()).job;
  const completed=app.store.submit(owner.id,JobRequestSchema.parse({type:'proxy',sourceId:originalSource.id}),randomUUID()).job;
  app.store.updateJob(completed.id,{state:'completed',artifactId:seeded[2].id});
  const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(15000);
  const session=await page.request.post(`${origin}/api/v1/session`,{headers:{origin},data:{token}});assert.equal(session.status(),200);
  await page.goto(origin);
  await page.getByRole('heading',{name:'Library',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Jobs',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Add media',exact:true}).count(),0);
  assert.equal(await page.locator('.media-card').count(),7);
  const expected=['download video.mkv','proxy video.mkv','export video.mkv','original video.mkv'];
  assert.deepEqual(await page.locator('[data-artifact-id] h3').allTextContents(),expected);
  assert.deepEqual((await(await page.request.get(`${origin}/api/v1/artifacts`)).json()).map((a:Artifact)=>a.name),expected);
  assert.equal(await page.locator(`[data-job-id="${completed.id}"]`).count(),0,'completed output is not duplicated');
  for(const card of await page.locator('[data-artifact-id]').all())await card.scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelectorAll('.library-thumbnail img').length===4&&[...document.querySelectorAll<HTMLImageElement>('.library-thumbnail img')].every(image=>image.complete&&image.naturalWidth>0));
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({animations:'disabled',path:path.join(evidence,'unified-library-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'In progress 2',exact:true}).click();assert.equal(await page.locator('.media-card').count(),2);
  assert(await page.getByRole('checkbox',{name:'Select all visible',exact:true}).isDisabled());
  await page.locator(`[data-job-id="${queued.id}"]`).getByRole('button',{name:'Cancel',exact:true}).click();
  await page.locator(`[data-job-id="${queued.id}"]`).waitFor({state:'hidden'});
  await page.getByRole('button',{name:/^Needs attention /}).click();assert.equal(await page.locator('.media-card').count(),2);
  await page.locator(`[data-job-id="${failure.id}"]`).getByRole('button',{name:'Retry',exact:true}).click();
  await page.locator(`[data-job-id="${failure.id}"]`).waitFor({state:'hidden'});assert.equal(app.store.job(failure.id)?.state,'queued');
  app.store.updateJob(failure.id,{state:'failed',error:'This video is unavailable. Check the link and retry.'});
  await page.getByRole('button',{name:/^All /}).click();
  await page.getByRole('checkbox',{name:'Select download video.mkv',exact:true}).check();
  await page.getByLabel('Search media',{exact:true}).fill('proxy');assert(await page.getByRole('button',{name:'Delete selected',exact:true}).isDisabled());
  assert.equal(await page.locator('.media-card').count(),1);
  await page.getByLabel('Search media',{exact:true}).fill('');
  await page.getByRole('checkbox',{name:'Select download video.mkv',exact:true}).check();
  await page.getByRole('checkbox',{name:'Select proxy video.mkv',exact:true}).check();
  await page.getByRole('button',{name:'Delete selected',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Delete selected items?',exact:true});
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();assert(app.store.get('artifact',seeded[1].id,owner.id));
  await page.getByRole('button',{name:'Delete selected',exact:true}).click();
  await dialog.getByRole('button',{name:'Delete 2 items',exact:true}).waitFor();
  app.store.put('artifact',seeded[3].id,owner.id,{...seeded[3],pinned:true});
  const deletedPath=await managedPath(app.store,seeded[1].id);
  await dialog.getByRole('button',{name:'Delete 2 items',exact:true}).click();await dialog.getByRole('alert').waitFor();
  assert.match(await dialog.getByRole('alert').innerText(),/Unpin/);assert.equal(await dialog.locator('.bulk-delete-list li').count(),1);
  await assert.rejects(access(deletedPath));app.store.put('artifact',seeded[3].id,owner.id,seeded[3]);
  await dialog.getByRole('button',{name:'Delete 1 item',exact:true}).click();await dialog.waitFor({state:'hidden'});
  await page.getByRole('checkbox',{name:'Select export video.mkv',exact:true}).check();
  await page.locator(`[data-job-id="${failure.id}"]`).getByRole('checkbox').check();
  await page.getByRole('button',{name:'Delete selected',exact:true}).click();
  assert.match(await dialog.innerText(),/1 library file/);assert.match(await dialog.innerText(),/1 activity entr/);
  await dialog.getByRole('button',{name:'Delete 2 items',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert(!app.store.get('artifact',seeded[2].id,owner.id));assert(!app.store.job(failure.id));assert(app.store.job(completed.id),'file removal retains activity history');
  assert.equal(await page.locator(`[data-job-id="${completed.id}"]`).count(),0,'removed files do not reappear as duplicate history rows');
  // A running download becomes exactly one ready file when it finishes.
  const staged=path.join(evidence,'coast-staged.mkv');await copyFile(fixture,staged);
  const result=await publish(app.store,staged,owner.id,'Coast video.mkv',media,'download');
  app.store.updateJob(download.id,{state:'completed',artifactId:result.id,progress:1});
  await page.locator(`[data-job-id="${download.id}"]`).waitFor({state:'hidden'});
  await page.locator(`[data-artifact-id="${result.id}"]`).waitFor();
  await page.getByRole('button',{name:'Preview Coast video.mkv',exact:true}).click();await page.locator('.library-preview video').waitFor();
  await page.getByRole('button',{name:'Close preview',exact:true}).click();
  await page.getByRole('button',{name:'Import',exact:true}).click();await page.getByRole('heading',{name:'Import',exact:true}).waitFor();
  assert(await page.getByRole('button',{name:'Choose files',exact:true}).isVisible());
  assert(!await page.getByLabel('Video or audio links',{exact:true}).isVisible());
  await page.screenshot({animations:'disabled',path:path.join(evidence,'import-files-desktop.png'),fullPage:true});
  await page.getByLabel('Local media',{exact:true}).setInputFiles([{name:'Garden walk.mkv',mimeType:'video/x-matroska',buffer:await readFile(fixture)},{name:'Evening sky.mkv',mimeType:'video/x-matroska',buffer:await readFile(fixture)}]);
  await page.getByRole('heading',{name:'Library',exact:true}).waitFor();
  assert.equal(await page.locator('.media-card h3').filter({hasText:'Garden walk.mkv'}).count(),1);
  assert.equal(await page.locator('.media-card h3').filter({hasText:'Evening sky.mkv'}).count(),1);
  await page.getByRole('button',{name:'Import',exact:true}).click();
  await page.getByRole('button',{name:'From a link',exact:true}).click();
  await page.route('**/api/v1/sources/inspect',route=>route.fulfill({json:{title:'A video from a link',entries:[]}}));
  await page.getByLabel('Video or audio links',{exact:true}).fill('https://example.com/new-video.mp4');
  await page.screenshot({animations:'disabled',path:path.join(evidence,'import-link-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Import link',exact:true}).click();await page.getByRole('heading',{name:'Library',exact:true}).waitFor();
  assert(app.store.jobs(owner.id).some(j=>j.request.type==='download'&&j.request.download.url==='https://example.com/new-video.mp4'));
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  for(const card of await page.locator('[data-artifact-id]').all())await card.scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('.library-thumbnail img')].length===4&&[...document.querySelectorAll<HTMLImageElement>('.library-thumbnail img')].every(image=>image.complete&&image.naturalWidth>0));
  await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({animations:'disabled',path:path.join(evidence,'unified-library-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Import',exact:true}).click();await page.getByRole('button',{name:'From a link',exact:true}).click();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({animations:'disabled',path:path.join(evidence,'import-link-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Back to library',exact:true}).click();
  await page.getByRole('button',{name:'Delete original video.mkv',exact:true}).click();
  await dialog.getByRole('button',{name:'Delete 1 item',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert(!app.store.get('artifact',seeded[0].id,owner.id));assert((await readFile(fixture)).length>0);
  await page.reload();await page.getByRole('heading',{name:'Library',exact:true}).waitFor();assert.equal(await page.locator(`[data-artifact-id="${seeded[0].id}"]`).count(),0);
  console.log('Passed: unified newest-first list, completed output deduplication, status/search filters, cancel/retry, bulk mixed deletion, protected-file retry, completion transition, previews, file/link import returning to library, original preservation, mobile layout and persistence.');
}finally{await browser.close();await app.close();}
