import React, { useEffect, useRef, useState } from 'react';
import { ExportSchema } from '../../../packages/contracts/src/index';
import type { Artifact, Capabilities, DownloadRequest, Job, Project, Source } from '../../../packages/contracts/src/index';
import { desktopBridge, browserCapabilities } from '../../../packages/platform/src/index';
import { shareXAction } from '../../../packages/platform/src/actions';
import { bytes, Checkbox, Field, NumberField, Panel } from '../../../packages/ui/src/index';
import { api, contentUrl, request, saveJson } from './api';
import { ArtifactActions } from './ArtifactActions';
type Task = (work:()=>Promise<unknown>)=>Promise<void>;
const terminalStates = ['completed','failed','cancelled','interrupted'];
const retryStates = ['failed','cancelled','interrupted'];
const statusNames: Record<Job['state'],string> = {queued:'Queued',preparing:'Preparing',downloading:'Downloading',processing:'Processing',validating:'Checking file',completed:'Completed',failed:'Failed',cancelling:'Cancelling',cancelled:'Cancelled',interrupted:'Interrupted'};
const mediaKinds: Record<Artifact['kind'],string> = {original:'Source',download:'Download',export:'Export',proxy:'Playback preview'};
function duration(seconds:number) {
  if (!Number.isFinite(seconds)) return 'Unknown duration';
  const value=Math.round(seconds), hours=Math.floor(value/3600), minutes=Math.floor(value%3600/60);
  return `${hours?`${hours}:`:''}${hours?String(minutes).padStart(2,'0'):minutes}:${String(value%60).padStart(2,'0')}`;
}
const dateTime=(value:string)=>new Date(value).toLocaleString();
function EmptyState({title,children}:{title:string;children:React.ReactNode}) {
  return <div className="page-empty"><h3>{title}</h3><p>{children}</p></div>;
}

function JobProgress({job,name}:{job:Job;name:string}) {
  if (terminalStates.includes(job.state)) {
    return <span className={`job-outcome job-outcome-${job.state}`}>{statusNames[job.state]}</span>;
  }
  if (job.state === 'queued') return <span className="job-waiting">Waiting to start</span>;
  const reported = ['downloading','processing'].includes(job.state) && Number.isFinite(job.progress) && job.progress > 0;
  const progress = reported ? Math.min(1, job.progress) : undefined;
  const label = job.state === 'preparing' ? (job.request.type === 'download' ? 'Preparing download' : 'Preparing media') : job.state === 'cancelling' ? 'Stopping job' : statusNames[job.state];
  return <div className="job-progress-content">
    <progress max={1} value={progress} aria-label={`${name}: ${label}`}/>
    <span>{reported ? (progress! < .01 ? '<1%' : `${Math.floor(progress! * 100)}%`) : label}</span>
    {!reported && ['downloading','processing'].includes(job.state) && <small>Progress not reported yet.</small>}
  </div>;
}

export function Input({caps,run,refresh,edit,setNotice}:{caps:Capabilities;run:Task;refresh:()=>Promise<void>;edit:(id:string)=>void;setNotice:(s:string)=>void}) {
  const [urls,setUrls]=useState(''),[format,setFormat]=useState(''),[preference,setPreference]=useState<DownloadRequest['preference']>('compatible'),[metadata,setMetadata]=useState<any>(),[cookieId,setCookieId]=useState(''),[cookies,setCookies]=useState<any[]>([]),[itemIndex,setItemIndex]=useState(1);
  const [working,setWorking]=useState<'import'|'inspect'|'download'>(),[dragging,setDragging]=useState(false);
  const inspectionVersion=useRef(0),selectedEntry=metadata?.entries?.find((entry:any)=>entry.itemIndex===itemIndex);
  const lines=urls.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),unique=[...new Set(lines)];
  useEffect(()=>{if(caps.mode==='local'&&caps.user.role==='owner')request<any[]>('/cookies').then(setCookies).catch(()=>{});},[]);
  const resetInspection=()=>{setMetadata(undefined);setItemIndex(1);setFormat('');inspectionVersion.current++;};
  const perform=(kind:'import'|'inspect'|'download',work:()=>Promise<unknown>)=>void run(async()=>{setWorking(kind);try{await work();}finally{setWorking(undefined);}});
  const upload=async(files:File[])=>{for(const file of files){const source=await api.upload(file);await refresh();edit(source.id);}};
  return <div className="support-page import-page">
    <div className="page-heading"><div><h1>Add media</h1><p>Choose a file or download from a link.</p></div></div>
    <div className="columns import-columns"><Panel title="Import media">
      <div className={`dropzone ${dragging?'is-dragging':''}`} onDragOver={e=>{e.preventDefault();if(caps.user.policy.upload&&!working)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(caps.user.policy.upload&&!working&&e.dataTransfer.files.length)perform('import',()=>upload(Array.from(e.dataTransfer.files)));}}>
        <svg className="import-file-icon" width="40" height="40" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M8 5h16l8 8v22H8V5Z" stroke="currentColor" strokeWidth="1.5"/><path d="M24 5v8h8M15 23l5-5 5 5M20 18v11" stroke="currentColor" strokeWidth="1.5"/></svg>
        <h3>Drop video or audio here</h3><p>Or choose files from your device.</p>
        <Field label="Local media"><input type="file" accept="video/*,audio/*,.mkv,.mov,.webm,.ts" multiple disabled={!caps.user.policy.upload||!!working} onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length)perform('import',()=>upload(files));e.target.value='';}}/></Field>
      </div><p className="page-note">A copy is added to your Library. Your original files stay unchanged.</p>
      <dl className="import-limits"><dt>File size limit</dt><dd>{bytes(caps.user.policy.maxInputBytes)} per file</dd><dt>File types</dt><dd>Video and audio</dd></dl>
      {!caps.user.policy.upload&&<p className="permission-note">Your account cannot import local files. Ask the workspace owner for access.</p>}{working==='import'&&<p className="inline-status" role="status">Importing media…</p>}
    </Panel><Panel title="Download from a link">
      <Field label="One URL per line"><textarea rows={5} value={urls} onChange={e=>{setUrls(e.target.value);resetInspection();}} placeholder="Paste a video or audio link" autoCapitalize="none" autoCorrect="off" spellCheck={false}/></Field>
      {lines.length>unique.length&&<p className="page-note">{lines.length-unique.length} duplicate {lines.length-unique.length===1?'link will':'links will'} be skipped.</p>}
      <div className="form-grid download-options"><Field label="Source preference"><select value={preference} onChange={e=>{setPreference(e.target.value as DownloadRequest['preference']);resetInspection();}}><option value="compatible">Easy to share (MP4 when available)</option><option value="original">Best available quality</option><option value="audio">Audio only</option></select></Field><Field label="Authentication"><select value={cookieId} onChange={e=>{setCookieId(e.target.value);resetInspection();}}><option value="">No saved account</option>{cookies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></div>
      <p className="page-note">Each link downloads one video. Inspect a link to choose a different video from the same post.</p>
      <div className="actions import-actions"><button disabled={unique.length!==1||!caps.user.policy.download||!!working} onClick={()=>perform('inspect',async()=>{const version=++inspectionVersion.current;const result=await api.inspect({url:unique[0],preference,...(cookieId?{cookieId}:{})});if(version===inspectionVersion.current){setMetadata(result);setItemIndex(result.entries?.[0]?.itemIndex||1);setFormat('');}})}>{working==='inspect'?'Inspecting…':'Inspect available media'}</button><button className="primary" disabled={!unique.length||!caps.user.policy.download||!!working} onClick={()=>perform('download',async()=>{const items=unique.map(url=>({url,preference,itemIndex:unique.length===1?itemIndex:1,...(format?{format}:{}),...(cookieId?{cookieId}:{})}));if(items.length===1)await api.submit({type:'download',download:items[0]});else await api.batch(items);await refresh();setNotice(`${items.length} download request${items.length===1?'':'s'} queued. See Jobs for progress and results.`);})}>{working==='download'?'Queueing…':`Queue ${unique.length>1?'batch':'download'}`}</button>{unique.length>1&&<span className="action-note">{unique.length} links</span>}</div>
      {!caps.user.policy.download&&<p className="permission-note">Your account cannot download media. Ask the workspace owner for access.</p>}
      <details className="settings-block"><summary>Advanced download options</summary><Field label="Provider format selector" help="Use a listed format ID or a yt-dlp selection expression. Command options are not accepted."><input value={format} onChange={e=>setFormat(e.target.value)} autoCapitalize="none" spellCheck={false}/></Field><p className="page-note">Downloads prefer a shareable MP4 when available. Other formats can be converted during export. A playlist link downloads the selected item only.</p></details>
      {metadata&&<section className="download-inspection" aria-label="Available media"><div className="section-heading"><h3>{metadata.title||'Available media'}</h3><span>{typeof metadata.duration==='number'?duration(metadata.duration):'Unknown duration'}</span></div>{metadata.authenticationNeeded===true&&<p className="permission-note">This link requires a signed-in account.</p>}
        {metadata.entries&&<><p className="page-note">{metadata.entries.length} {metadata.entries.length===1?'item':'items'} found. One selected item will download.{metadata.limitReached&&' Showing the first 100 items.'}</p>{metadata.entries.length>0&&<Field label="Media item to download"><select value={itemIndex} onChange={e=>{setItemIndex(Number(e.target.value));setFormat('');}}>{metadata.entries.map((entry:any)=><option key={entry.itemIndex} value={entry.itemIndex}>{entry.itemIndex}. {entry.title||entry.id||'Media'}{typeof entry.duration==='number'?` (${duration(entry.duration)})`:''}</option>)}</select></Field>}</>}
        <details open className="settings-block"><summary>Available formats{format?` — selected ${format}`:''}</summary><div className="table-scroll"><table className="formats-table"><thead><tr><th>Select</th><th>Format</th><th>Resolution</th><th>Video / audio</th><th>Estimated size</th></tr></thead><tbody>{(selectedEntry?.formats||[]).map((f:any)=><tr key={f.format_id||f.id}><td data-label="Select"><button aria-pressed={format===String(f.format_id||f.id)} onClick={()=>setFormat(String(f.format_id||f.id))}>Use</button></td><td data-label="Format">{f.format_id||f.id} ({f.ext})</td><td data-label="Resolution">{f.width&&f.height?`${f.width} × ${f.height}`:f.resolution||'Not provided'}</td><td data-label="Video / audio">{f.vcodec||'None'} / {f.acodec||'None'}</td><td data-label="Estimated size">{f.bytes||f.filesize||f.filesize_approx?bytes(f.bytes||f.filesize||f.filesize_approx):'Unknown'}</td></tr>)}</tbody></table></div>{!(selectedEntry?.formats||[]).length&&<p className="page-note">No individual formats were returned. The source preference will choose a format automatically.</p>}</details>
      </section>}
    </Panel></div>
  </div>;
}
export function Queue({jobs,sources,artifacts,run,refresh,edit,setNotice}:{sources:Source[];artifacts:Artifact[];jobs:Job[];run:Task;refresh:()=>Promise<void>;edit:(id:string)=>void;setNotice:(s:string)=>void}) {
  const [filter,setFilter]=useState('all');
  const batches=[...new Set(jobs.map(j=>j.batchId).filter(Boolean))] as string[];
  const act=(path:string)=>void run(async()=>{await api.action(path);await refresh();});
  const removeHistory=(job:Job)=>{if(!window.confirm('Delete this completed job history entry? Its media files will be retained.'))return;void run(async()=>{await api.remove('/jobs/'+job.id);await refresh();setNotice('Job history deleted. Media files retained.');});};
  const pending=jobs.filter(j=>j.state==='queued').sort((a,b)=>a.position-b.position);
  const move=(id:string,offset:number)=>void run(async()=>{const ids=pending.map(j=>j.id),i=ids.indexOf(id);if(i<0||i+offset<0||i+offset>=ids.length)return;[ids[i],ids[i+offset]]=[ids[i+offset],ids[i]];await api.action('/jobs/reorder',{ids});await refresh();});
  const active=jobs.filter(j=>!terminalStates.includes(j.state)).length,completed=jobs.filter(j=>j.state==='completed').length,attention=jobs.filter(j=>retryStates.includes(j.state)).length;
  const visible=jobs.filter(j=>filter==='all'||(filter==='active'?!terminalStates.includes(j.state):filter==='completed'?j.state==='completed':retryStates.includes(j.state)));
  return <div className="support-page jobs-page"><div className="page-heading"><div><h1>Jobs</h1><p>{active?`${active} in progress`:'Downloads, previews and exports.'}</p></div><details className="history-download"><summary>Save history</summary><div className="actions"><button onClick={()=>saveJson('media-results.json',jobs)}>Export results JSON</button><a href="/api/v1/history/export?format=csv" download="media-results.csv">Export results CSV</a></div></details></div><Panel title="Jobs and history">
    <div className="jobs-toolbar"><div className="filter-buttons" aria-label="Filter jobs">{[['all','All',jobs.length],['active','In progress',active],['completed','Completed',completed],['attention','Needs attention',attention]].map(([value,label,count])=><button key={String(value)} aria-pressed={filter===value} onClick={()=>setFilter(String(value))}>{label} <span>{count}</span></button>)}</div></div>
    {!!batches.length&&<details className="settings-block batch-list"><summary>Download batches ({batches.length})</summary>{batches.map(id=>{const items=jobs.filter(j=>j.batchId===id);return <div className="batch" key={id}><div className="batch-name"><strong>Batch {id.slice(0,8)}</strong><small>{items.filter(j=>j.state==='completed').length} of {items.length} completed</small></div><div className="actions"><button onClick={()=>act(`/batches/${id}/cancel`)} disabled={!items.some(j=>!terminalStates.includes(j.state))}>Cancel batch</button><button onClick={()=>act(`/batches/${id}/retry`)} disabled={!items.some(j=>retryStates.includes(j.state))}>Retry failed</button></div></div>;})}</details>}
    {!visible.length?<EmptyState title={jobs.length?'No matching jobs':'No jobs yet'}>{jobs.length?'Choose another filter to see your job history.':'Download a link or export from the editor. Progress and results appear here.'}</EmptyState>:<div className="table-scroll jobs-scroll"><table className="jobs-table"><thead><tr><th>Request</th><th>Status</th><th>Progress</th><th>Actions</th></tr></thead><tbody>{visible.map(j=>{const finished=terminalStates.includes(j.state);const name=sources.find(s=>s.id===j.sourceId)?.name||artifacts.find(a=>a.id===j.artifactId)?.name||(j.request.type==='download'?'Download':j.request.type==='proxy'?'Playback preview':'Export');return <tr key={j.id}><td data-label="Request" className="job-request"><strong>{name}</strong><small>{j.request.type==='download'?j.request.download.url:j.request.type==='proxy'?'Playback preview':'Export'}</small><small>{dateTime(j.createdAt)}{j.attempt>1?` · Attempt ${j.attempt}`:''}</small></td><td data-label="Status"><span className={`job-state job-state-${j.state}`}>{statusNames[j.state]}</span>{j.message&&!j.error&&<small>{j.message}</small>}{j.error&&<div className="job-error"><strong>{j.request.type==="download"?"Download error":"Job error"}</strong><p>{j.error}</p></div>}{j.plan&&<details className="job-plan"><summary>Processing details</summary><pre>{JSON.stringify(j.plan,null,2)}</pre></details>}</td><td data-label="Progress" className="job-progress"><JobProgress job={j} name={name}/></td><td data-label="Actions"><div className="actions job-actions">{!finished&&<button onClick={()=>act(`/jobs/${j.id}/cancel`)}>Cancel</button>}{retryStates.includes(j.state)&&<button className="primary" onClick={()=>act(`/jobs/${j.id}/retry`)}>Retry</button>}{j.sourceId&&<button onClick={()=>edit(j.sourceId!)}>Edit source</button>}{j.artifactId&&<a href={contentUrl(j.artifactId)} download>Download result</a>}{j.state==='queued'&&<><button disabled={pending[0]?.id===j.id} onClick={()=>move(j.id,-1)} aria-label={`Move ${j.id} up`}>Move up</button><button disabled={pending.at(-1)?.id===j.id} onClick={()=>move(j.id,1)} aria-label={`Move ${j.id} down`}>Move down</button></>}{finished&&<button className="quiet" onClick={()=>removeHistory(j)}>Delete history only</button>}</div></td></tr>;})}</tbody></table></div>}
  </Panel></div>;
}
export function Library({sources,artifacts,run,refresh,edit,setNotice}:{sources:Source[];artifacts:Artifact[];run:Task;refresh:()=>Promise<void>;edit:(id:string)=>void;setNotice:(s:string)=>void}) {
  const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[preview,setPreview]=useState<string>(),[previewError,setPreviewError]=useState(''),[copyAvailable,setCopyAvailable]=useState(false);
  useEffect(()=>{desktopBridge()?.capabilities().then(c=>setCopyAvailable(c.fileClipboard?.state==='available')).catch(()=>{});},[]);
  const latest=artifacts.filter(a=>a.validated&&['export','download'].includes(a.kind)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
  const filtered=artifacts.filter(a=>a.name.toLowerCase().includes(query.toLowerCase())&&(kind==='all'||(kind==='sources'?sources.some(s=>s.artifactId===a.id):a.kind===kind))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const deleteMedia=(artifact:Artifact)=>{const imported=artifact.kind==='original';if(!window.confirm(imported?'Permanently delete this managed imported copy of '+artifact.name+'? The file at its original import location and job history will remain.':'Permanently delete the managed media file '+artifact.name+'? Job history will remain.'))return;void run(async()=>{await request('/artifacts/'+artifact.id,{method:'DELETE',...(imported?{body:JSON.stringify({confirmOriginal:true})}:{})});setPreview(undefined);await refresh();setNotice('Managed media deleted. Job history retained.');});};
  return <div className="library-page"><Panel title="Media library"><div className="library-tools"><Field label="Search media"><input type="search" placeholder="Search file names" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Show media"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All media</option><option value="sources">Sources</option><option value="export">Exports</option><option value="download">Downloads</option><option value="proxy">Playback previews</option></select></Field><span className="library-count">{filtered.length} {filtered.length===1?'file':'files'}</span>{desktopBridge()&&<button disabled={!latest||!copyAvailable} onClick={()=>void run(async()=>{await desktopBridge()!.copyFile(latest.id);setNotice(`Copied latest successful output for this user: ${latest.name}`);})}>Copy latest output file</button>}</div>
    {!filtered.length&&<EmptyState title={artifacts.length?'No matching media':'Your Library is empty'}>{artifacts.length?'Try another file name or choose All media.':'Use Add media to import a file or download from a link.'}</EmptyState>}
    <div className="library media-list">{filtered.map(a=>{const source=sources.find(s=>s.artifactId===a.id),video=a.media.streams.find(s=>s.type==='video'),audioOnly=!video&&a.media.streams.some(s=>s.type==='audio');return <article className="media-card" key={a.id}>
      <div className="media-card-heading"><div className="media-file-mark" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d={audioOnly?'M9 17V6l11-2v11M9 10l11-2':'M3 5h14v14H3V5Zm14 4 5-3v12l-5-3'} stroke="currentColor" strokeWidth="1.5"/>{audioOnly&&<><ellipse cx="6" cy="18" rx="3" ry="2" stroke="currentColor" strokeWidth="1.5"/><ellipse cx="17" cy="16" rx="3" ry="2" stroke="currentColor" strokeWidth="1.5"/></>}</svg></div><div className="media-name"><h3>{a.name}</h3><div className="media-facts"><span>{mediaKinds[a.kind]}</span><span>{duration(a.media.duration)}</span><span>{bytes(a.bytes)}</span>{video?.width&&video.height&&<span>{video.width} × {video.height}</span>}{a.pinned&&<span className="protected-label">Protected</span>}</div></div><div className="actions media-primary-actions"><button aria-expanded={preview===a.id} onClick={()=>{setPreview(preview===a.id?undefined:a.id);setPreviewError('');}}>{preview===a.id?'Close preview':'Preview'}</button>{source&&<button className="primary" onClick={()=>edit(source.id)}>Edit source</button>}</div></div>
      {preview===a.id&&<div className="library-preview">{audioOnly?<audio controls src={contentUrl(a.id)} preload="metadata" onError={()=>setPreviewError(a.id)}/>:<video controls src={contentUrl(a.id)} preload="metadata" onError={()=>setPreviewError(a.id)}/>}<small>File preview</small>{previewError===a.id&&<p className="permission-note">This browser cannot play the file. Open the source in the editor and create a playback preview.</p>}</div>}
      <div className="media-card-actions"><ArtifactActions artifact={a} run={run} setNotice={setNotice}/><details className="media-manage"><summary>File details</summary><dl className="file-details"><dt>Added</dt><dd>{dateTime(a.createdAt)}</dd><dt>File check</dt><dd>{a.validated?'Passed':'Not checked'}</dd><dt>Storage</dt><dd>{a.pinned?'Protected from deletion':'Managed copy'}</dd></dl><details><summary>Technical metadata</summary><pre>{JSON.stringify(a.media,null,2)}</pre></details></details><button className="quiet" disabled={a.pinned} title={a.pinned?'Pinned media is protected from deletion.':undefined} onClick={()=>deleteMedia(a)}>{a.kind==='original'?'Delete imported copy':'Delete media file'}</button></div>
    </article>;})}</div>
  </Panel></div>;
}
export function SavedProjects({run,onProject}:{run:Task;onProject:(p:Project)=>void}) {
  const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true);
  const load=async()=>{try{setProjects(await api.projects());}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="projects-page"><Panel title="Saved projects">{loading?<p className="inline-status" role="status">Loading projects…</p>:!projects.length&&<EmptyState title="No saved projects">Save a project in the editor to keep its source, edits and export settings together.</EmptyState>}<div className="project-list">{projects.map(p=><article className="row project-row" key={p.id}><div className="project-name"><strong>{p.name}</strong><small>Updated {dateTime(p.updatedAt)}</small></div><div className="actions"><button onClick={()=>onProject(p)}>Load project</button><details className="project-manage"><summary>More</summary><button className="quiet" onClick={()=>void run(async()=>{await api.remove(`/projects/${p.id}`);await load();})}>Delete project recipe</button><p className="page-note">Media files are kept.</p></details></div></article>)}</div></Panel></div>;
}

export function Presets({run}:{run:Task;onProject:(p:Project)=>void}) {
  const [presets,setPresets]=useState<any[]>([]),[payload,setPayload]=useState(''),[validation,setValidation]=useState<any>(),[loading,setLoading]=useState(true);
  const load=async()=>{try{setPresets(await request<any[]>('/presets'));}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="columns settings-columns presets-page"><Panel title="Export presets"><p className="page-note">Reuse export settings across projects. Presets contain settings only.</p>{loading?<p className="inline-status" role="status">Loading presets…</p>:!presets.length&&<EmptyState title="No saved presets">Import a preset file or create one using the form.</EmptyState>}{presets.map(item=><article key={item.id||item.preset?.id} className="row preset-row"><strong>{item.name||item.preset?.name}</strong><button onClick={()=>void run(async()=>saveJson('media-preset.json',await request(`/presets/${item.id}`)))}>Export JSON</button></article>)}</Panel>
    <Panel title="Import or create a preset"><Field label="Open preset JSON"><input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{setPayload(await f.text());setValidation(undefined);});e.target.value='';}}/></Field><div className="actions"><button onClick={()=>{setPayload(JSON.stringify({schemaVersion:1,id:'my-sharing-preset',revision:1,name:'My sharing preset',requires:['exact-cut-v1','target-size-v1'],options:ExportSchema.parse({cut:'exact',mode:'size',maxBytes:20_000_000})},null,2));setValidation(undefined);}}>New editable preset</button></div><Field label="Preset JSON"><textarea className="json-input" rows={12} value={payload} spellCheck={false} onChange={e=>{setPayload(e.target.value);setValidation(undefined);}}/></Field><div className="actions"><button disabled={!payload.trim()} onClick={()=>void run(async()=>setValidation(await api.action('/presets/validate',JSON.parse(payload))))}>Validate preset</button><button className="primary" disabled={!validation} onClick={()=>void run(async()=>{await api.action('/presets/import',JSON.parse(payload));await load();})}>Import validated preset</button></div>{validation&&<div className="preset-validation"><h3>Validation result</h3><pre>{JSON.stringify(validation,null,2)}</pre></div>}</Panel>
  </div>;
}
const nativeLabels:Record<string,string>={fileClipboard:'Copy files',pathClipboard:'Copy paths',revealFile:'Show file location',saveAs:'Save a copy',nativeDragOut:'Drag files to another app',externalActions:'Open in other apps'};
export function Integrations({caps,run,setNotice}:{caps:Capabilities;run:Task;setNotice:(s:string)=>void}) {
  const bridge=desktopBridge(),[native,setNative]=useState<Record<string,{state:string;reason?:string}>>(browserCapabilities),[actions,setActions]=useState<any[]>([]),[cookies,setCookies]=useState<any[]>([]),[loading,setLoading]=useState(true);
  const [name,setName]=useState('Open in editor'),[args,setArgs]=useState('["{file}"]'),[uploads,setUploads]=useState(false),[timeoutSeconds,setTimeoutSeconds]=useState(30),[browser,setBrowser]=useState('chrome'),[profile,setProfile]=useState(''),[shareXTask,setShareXTask]=useState('');
  const load=async()=>{try{if(bridge){setNative(await bridge.capabilities());setActions(await bridge.listActions());}if(caps.mode==='local'&&caps.user.role==='owner')setCookies(await request('/cookies'));}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="columns settings-columns integrations-page"><Panel title="Desktop integrations"><p className="page-note">Copy files, find their location or open them in another app.</p><div className="capability-list">{Object.entries(native).map(([key,v])=><div className="capability-row" key={key}><strong>{nativeLabels[key]||key}</strong><span className="capability-state">{v.state==='available'?'Available':v.state==='permission-denied'?'Permission needed':'Unavailable'}</span>{v.reason&&<small>{v.reason}</small>}</div>)}</div>
    {bridge?<details className="settings-block"><summary>Open files in another app</summary><p className="page-note">Choose an app on this computer. Actions that upload a file ask for confirmation each time.</p>{actions.map(a=><div className="row" key={a.id}><strong>{a.name}</strong><span>{a.uploads?'Uploads files':'Local app'} · {a.timeoutSeconds} second limit</span></div>)}<Field label="Action name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Argument array JSON" help="Placeholders: {file}, {filename}, {directory}. Each item is one argument; a command shell is never used."><textarea className="json-input" value={args} onChange={e=>setArgs(e.target.value)} spellCheck={false}/></Field><NumberField label="Action timeout (seconds)" value={timeoutSeconds} min={1} max={300} step={1} onChange={setTimeoutSeconds}/><Checkbox label="This action uploads media to another service" value={uploads} onChange={setUploads}/><button disabled={!name.trim()} onClick={()=>void run(async()=>{await bridge.configureAction({name,args:JSON.parse(args),uploads,timeoutSeconds});await load();setNotice('Local binding dialog completed. Saved bindings appear above.');})}>Choose executable and save binding</button><details className="settings-block"><summary>ShareX setup</summary><Field label="Configured ShareX task name"><input value={shareXTask} onChange={e=>setShareXTask(e.target.value)}/></Field><button disabled={!shareXTask.trim()} onClick={()=>void run(async()=>{await bridge.configureAction(shareXAction(shareXTask));await load();setNotice('ShareX binding dialog completed. Handoffs always require local upload confirmation.');})}>Choose ShareX.exe and register task</button><p className="page-note">Choose the installed ShareX.exe and check the named task in ShareX first. Each upload requires confirmation on this computer. An app finishing does not confirm that an upload succeeded.</p></details></details>:<p className="permission-note">These actions are available in the desktop app. In a browser, use Download file to save media.</p>}
    </Panel><Panel title="Download accounts">{caps.mode==='local'&&caps.user.role==='owner'?<><p className="page-note">Save account cookies for links that require sign-in. Choose a saved account explicitly when downloading.</p><p className="permission-note">Cookies may give access to signed-in sessions. Import only accounts you intend this local service to use.</p>{loading&&<p className="inline-status" role="status">Loading saved accounts…</p>}{!loading&&!cookies.length&&<p className="page-note">No saved accounts.</p>}{cookies.map(c=><div className="row credential-row" key={c.id}><span>{c.name}{c.browser?` (${c.browser})`:''}</span><button onClick={()=>void run(async()=>{await api.remove(`/cookies/${c.id}`);await load();})}>Forget credential</button></div>)}<Field label="Netscape cookies file"><input type="file" accept=".txt" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{await api.action('/cookies/import',{name:file.name,content:await file.text()});await load();setNotice('Cookie credential imported locally. Select it explicitly on each download.');});e.target.value='';}}/></Field><details className="settings-block"><summary>Use a local browser account</summary><div className="form-grid"><Field label="Local browser"><select value={browser} onChange={e=>setBrowser(e.target.value)}>{['chrome','edge','firefox','chromium','brave','opera','vivaldi'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Profile name (optional)"><input value={profile} onChange={e=>setProfile(e.target.value)}/></Field></div><button onClick={()=>void run(async()=>{await api.action('/cookies/browser',{browser,...(profile?{profile}:{})});await load();setNotice('Browser-profile credential registered. Extraction happens when the selected download runs; permission or encryption failures appear in Jobs.');})}>Use this local browser profile</button><p className="page-note">Cookies are read when a download runs. Browser permissions and encryption still apply.</p></details></>:<p className="permission-note">Saved browser accounts are available only to the owner of a local workspace. Shared hosting cannot use host browser sessions or guest cookie imports.</p>}</Panel>
  </div>;
}
export function Settings({caps,run,setNotice}:{caps:Capabilities;run:Task;setNotice:(s:string)=>void}) {
  const [concurrency,setConcurrency]=useState(1),[maxConcurrency,setMaxConcurrency]=useState(caps.user.policy.concurrency),[diagnostics,setDiagnostics]=useState<any>(),[loading,setLoading]=useState(true);
  useEffect(()=>{void run(async()=>{try{const v=await request<any>('/settings');setConcurrency(v.concurrency);setMaxConcurrency(v.maxConcurrency);}finally{setLoading(false);}});},[]);
  return <div className="columns settings-columns general-settings"><Panel title="Processing"><NumberField label="Maximum concurrent jobs" value={concurrency} min={1} max={maxConcurrency} step={1} disabled={caps.user.role!=='owner'||loading} onChange={setConcurrency}/><p className="page-note">Run up to {maxConcurrency} {maxConcurrency===1?'job':'jobs'} at once. Downloads run one at a time by default.</p><button className="primary" disabled={caps.user.role!=='owner'||loading} onClick={()=>void run(async()=>{const result=await api.patch('/settings',{concurrency});setConcurrency(result.concurrency);setNotice('Concurrency setting saved.');})}>Save concurrency</button>{caps.user.role!=='owner'&&<p className="permission-note">Only the workspace owner can change this setting.</p>}<details className="settings-block"><summary>Account permissions and limits</summary><dl className="permission-list"><dt>Import files</dt><dd>{caps.user.policy.upload?'Allowed':'Unavailable'}</dd><dt>Download links</dt><dd>{caps.user.policy.download?'Allowed':'Unavailable'}</dd><dt>Edit and export</dt><dd>{caps.user.policy.process?'Allowed':'Unavailable'}</dd><dt>Input size</dt><dd>{bytes(caps.user.policy.maxInputBytes)}</dd><dt>Output size</dt><dd>{bytes(caps.user.policy.maxOutputBytes)}</dd></dl><details><summary>Full permission details</summary><pre>{JSON.stringify(caps.user.policy,null,2)}</pre></details></details></Panel>
    <Panel title="Tools and support"><p className="page-note">Check available media tools or prepare support information for review.</p><dl className="tools-list">{Object.entries(caps.tools).map(([name,v])=><React.Fragment key={name}><dt>{name}</dt><dd>{v}</dd></React.Fragment>)}</dl><details className="settings-block"><summary>Available video encoders</summary><div className="table-scroll"><table className="encoders-table"><thead><tr><th>Encoder</th><th>Processing</th><th>Status</th></tr></thead><tbody>{caps.encoders.map(e=><tr key={e.name}><td data-label="Encoder">{e.name}<small>{e.codec}</small></td><td data-label="Processing">{e.hardware?'Graphics card':'Processor'}</td><td data-label="Status">{e.available?'Available':'Unavailable'}{e.reason&&<small>{e.reason}</small>}<small>Checked {dateTime(e.testedAt)}</small></td></tr>)}</tbody></table></div><p className="page-note">Graphics card encoding does not guarantee faster decoding or effects. Experimental hybrid cutting is disabled.</p></details><button onClick={()=>void run(async()=>setDiagnostics(await request('/diagnostics')))}>Prepare support data</button>{diagnostics&&<div className="support-data"><h3>Review before saving</h3><p className="page-note">This data is redacted. Review it before sharing it with support.</p><pre>{JSON.stringify(diagnostics,null,2)}</pre><button onClick={()=>saveJson('media-workbench-diagnostics.json',diagnostics)}>Save reviewed support data</button></div>}</Panel>
  </div>;
}

export function Administration({run,setNotice}:{run:Task;setNotice:(s:string)=>void}) {
  const [users,setUsers]=useState<any[]>([]),[pairings,setPairings]=useState<any[]>([]),[loading,setLoading]=useState(true),[name,setName]=useState(''),[role,setRole]=useState('restricted-guest'),[credential,setCredential]=useState(''),[pairName,setPairName]=useState('Browser client'),[policy,setPolicy]=useState(''),[userId,setUserId]=useState('');
  const load=async()=>{try{const [u,p]=await Promise.all([request<any[]>('/admin/users'),request<any[]>('/pairings')]);setUsers(u);setPairings(p);}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="administration-page">{credential&&<div className="notice credential-notice"><h3>Save this access token now</h3><p>It is shown only once. Keep it private.</p><code className="secret">{credential}</code><button onClick={()=>setCredential('')}>Hide credential</button></div>}<div className="columns settings-columns"><Panel title="Users"><p className="page-note">Choose who can download media or use the editor.</p><div className="form-grid"><Field label="New user name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="New user role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="restricted-guest">Guest — download only</option><option value="member">Member — edit and export</option></select></Field></div><button className="primary" disabled={!name.trim()} onClick={()=>void run(async()=>{const result=await api.action('/admin/users',{name,role});setCredential(result.token||result.credential||'');await load();})}>Create user</button>
    {loading?<p className="inline-status" role="status">Loading users…</p>:<div className="table-scroll"><table className="users-table"><thead><tr><th>Name</th><th>Role</th><th>Limits</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td data-label="Name">{u.name}</td><td data-label="Role">{u.role==='owner'?'Owner':u.role==='member'?'Member':'Guest'}</td><td data-label="Limits"><button onClick={()=>{setUserId(u.id);setPolicy(JSON.stringify(u.policy,null,2));}}>Edit limits</button></td></tr>)}</tbody></table></div>}{userId&&<div className="policy-editor"><h3>Limits for {users.find(u=>u.id===userId)?.name||'selected user'}</h3><Field label="Selected user policy JSON"><textarea className="json-input" rows={12} value={policy} onChange={e=>setPolicy(e.target.value)} spellCheck={false}/></Field><div className="actions"><button className="primary" onClick={()=>void run(async()=>{await api.patch(`/admin/users/${userId}`,{policy:JSON.parse(policy)});await load();setNotice('User limits saved and enforced by the service.');})}>Save selected user policy</button><button onClick={()=>{setUserId('');setPolicy('');}}>Close limits</button></div></div>}
    </Panel><Panel title="Connected clients"><p className="page-note">Allow a browser extension or another client to read the workspace and submit jobs. Access can be revoked here.</p><Field label="Client name"><input value={pairName} onChange={e=>setPairName(e.target.value)}/></Field><button disabled={!pairName.trim()} onClick={()=>void run(async()=>{const result=await api.action('/pairings',{name:pairName,scopes:['read','submit']});setCredential(result.token||result.credential||'');await load();})}>Create scoped pairing</button><p className="permission-note">Keep access tokens out of URLs and extension content scripts.</p>{!loading&&!pairings.length&&<p className="page-note">No connected clients.</p>}{pairings.map(p=><div className="row pairing-row" key={p.id}><div><strong>{p.name}</strong><small>{(p.scopes||[]).join(', ')}</small></div><button onClick={()=>void run(async()=>{await api.remove(`/pairings/${p.id}`);await load();})}>Revoke pairing</button></div>)}<details className="settings-block"><summary>Storage cleanup</summary><p className="page-note">Remove eligible managed files according to this workspace’s retention rules.</p><button onClick={()=>void run(async()=>{const result=await api.action('/retention');setNotice(`Retention run completed: ${JSON.stringify(result)}`);})}>Run managed retention cleanup</button></details></Panel></div>
  </div>;
}
