import React, { useEffect, useRef, useState } from 'react';
import { ExportSchema } from '../../../packages/contracts/src/index';
import type { Artifact, Capabilities, DownloadRequest, Job, Project, Source } from '../../../packages/contracts/src/index';
import { desktopBridge, browserCapabilities } from '../../../packages/platform/src/index';
import { shareXAction } from '../../../packages/platform/src/actions';
import { bytes, Checkbox, Field, NumberField, Panel } from '../../../packages/ui/src/index';
import { api, contentUrl, request, saveJson } from './api';
import { ArtifactActions } from './ArtifactActions';
import { useBulkDelete } from './BulkDelete';
import { LibraryThumbnail } from './LibraryThumbnail';
import { downloadQualities } from './downloadQuality';
import { LinkImport } from './LinkImport';
import { EditorIcon, type IconTone } from './EditorIcon';
type Task = (work:()=>Promise<unknown>)=>Promise<void>;
const terminalStates = ['completed','failed','cancelled','interrupted'];
const retryStates = ['failed','cancelled','interrupted'];
const statusNames: Record<Job['state'],string> = {queued:'Queued',preparing:'Preparing',downloading:'Downloading',processing:'Processing',validating:'Checking file',completed:'Completed',failed:'Failed',cancelling:'Cancelling',cancelled:'Cancelled',interrupted:'Interrupted'};
const mediaKinds: Record<Artifact['kind'],string> = {original:'Source',download:'Download',export:'Export',proxy:'Playback preview'};
const stateTones: Partial<Record<Job['state'],IconTone>> = {completed:'ok',failed:'danger',interrupted:'warn',downloading:'info',processing:'info',validating:'info',preparing:'info'};
function duration(seconds:number) {
  if (!Number.isFinite(seconds)) return 'Unknown duration';
  const value=Math.round(seconds), hours=Math.floor(value/3600), minutes=Math.floor(value%3600/60);
  return `${hours?`${hours}:`:''}${hours?String(minutes).padStart(2,'0'):minutes}:${String(value%60).padStart(2,'0')}`;
}
const dateTime=(value:string)=>new Date(value).toLocaleString();
function EmptyState({title,icon='info'}:{title:string;icon?:string}) {
  return <div className="page-empty"><EditorIcon name={icon} size={20}/><h3>{title}</h3></div>;
}

function JobProgress({job,name}:{job:Job;name:string}) {
  if (terminalStates.includes(job.state)) {
    return null;
  }
  if (job.state === 'queued') return <span className="job-waiting">Waiting to start</span>;
  const reported = ['downloading','processing','validating'].includes(job.state) && Number.isFinite(job.progress) && job.progress > 0;
  const progress = reported ? Math.min(1, job.progress) : undefined;
  const label = job.state === 'preparing' ? (job.request.type === 'download' ? 'Preparing download' : 'Preparing media') : job.state === 'cancelling' ? 'Stopping job' : statusNames[job.state];
  return <div className="job-progress-content">
    <progress max={1} value={progress} aria-label={`${name}: ${label}`}/>
    <span>{reported ? `${job.state === 'validating' ? 'Checking file: ' : ''}${progress! < .01 ? '<1%' : `${Math.floor(progress! * 100)}%`}` : label}</span>
  </div>;
}

export function Input({caps,run,refresh,done,setNotice}:{caps:Capabilities;run:Task;refresh:()=>Promise<void>;done:()=>void;setNotice:(s:string)=>void}) {
  const [method,setMethod]=useState<'files'|'links'>('files'),[uploadStatus,setUploadStatus]=useState('');
  const fileInput=useRef<HTMLInputElement>(null);
  const [urls,setUrls]=useState(''),[format,setFormat]=useState(''),[preference,setPreference]=useState<DownloadRequest['preference']>('compatible'),[metadata,setMetadata]=useState<any>(),[cookieId,setCookieId]=useState(''),[cookies,setCookies]=useState<any[]>([]),[itemIndex,setItemIndex]=useState(1);
  const [working,setWorking]=useState<'import'|'inspect'|'download'>(),[dragging,setDragging]=useState(false),[inspectionError,setInspectionError]=useState('');
  const inspecting=useRef<{key:string;promise:Promise<any>}|undefined>(undefined);
  const inspectionVersion=useRef(0),selectedEntry=metadata?.entries?.find((entry:any)=>entry.itemIndex===itemIndex);
  const lines=urls.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),unique=[...new Set(lines)];
  useEffect(()=>{if(caps.mode==='local'&&caps.user.role==='owner')request<any[]>('/cookies').then(setCookies).catch(()=>{});},[]);
  const resetInspection=()=>{setMetadata(undefined);setItemIndex(1);setFormat('');setInspectionError('');setWorking(current=>current==='inspect'?undefined:current);inspectionVersion.current++;};
  const inspectLink=async()=>{
    if(unique.length!==1)return;
    const version=inspectionVersion.current,key=JSON.stringify([unique[0],cookieId,preference]);
    setWorking('inspect');setInspectionError('');
    if(inspecting.current?.key!==key)inspecting.current={key,promise:api.inspect({url:unique[0],preference,...(cookieId?{cookieId}:{})})};
    try{const result=await inspecting.current.promise;if(version===inspectionVersion.current){setMetadata(result);setItemIndex(result.entries?.[0]?.itemIndex||1);setFormat('');}}
    catch(error){if(version===inspectionVersion.current)setInspectionError(error instanceof Error?error.message:'Cannot inspect this link');inspecting.current=undefined;}
    finally{if(version===inspectionVersion.current)setWorking(undefined);}
  };
  useEffect(()=>{
    if(unique.length!==1||!caps.user.policy.download)return;
    try{const parsed=new URL(unique[0]);if(!['http:','https:'].includes(parsed.protocol))return;}catch{return;}
    const timer=window.setTimeout(()=>void inspectLink(),700);
    return()=>window.clearTimeout(timer);
  },[urls,cookieId,preference]);
  const qualities=preference==='audio'?[]:downloadQualities(selectedEntry?.formats||[],preference==='compatible');
  const perform=(kind:'import'|'inspect'|'download',work:()=>Promise<unknown>)=>void run(async()=>{setWorking(kind);try{await work();}finally{setWorking(undefined);}});
  const upload=async(files:File[])=>{const failed:string[]=[];let count=0;for(const [index,file] of files.entries()){setUploadStatus(`Importing ${index+1} of ${files.length}: ${file.name}`);try{await api.upload(file);count++;}catch(error){failed.push(`${file.name}: ${error instanceof Error?error.message:String(error)}`);}}await refresh();setUploadStatus('');if(failed.length)throw new Error(`Imported ${count} of ${files.length} files. ${failed.join('; ')}`);done();setNotice(`Imported ${count} ${count===1?'file':'files'}. Select a video to preview or edit.`);};
  return <div className="support-page import-page">
    <div className="page-heading" hidden={method==="links"}><div><h1>Import</h1><p>Choose files or paste a link. Everything appears in your Library.</p></div><button disabled={!!working} onClick={done}>Back to library</button></div><div className="filter-buttons import-methods" aria-label="Import method"><button aria-pressed={method==='files'} disabled={!!working} onClick={()=>setMethod('files')}><EditorIcon name="upload" size={18}/>From files</button><button aria-pressed={method==='links'} disabled={!!working} onClick={()=>setMethod('links')}><EditorIcon name="download" size={18}/>From a link</button></div>
    <div className="import-body"><section hidden={method!=='files'}><Panel title="From your computer">
      <div className={`dropzone ${dragging?'is-dragging':''}`} onDragOver={e=>{e.preventDefault();if(caps.user.policy.upload&&!working)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(caps.user.policy.upload&&!working&&e.dataTransfer.files.length)perform('import',()=>upload(Array.from(e.dataTransfer.files)));}}>
        <EditorIcon name="upload" size={36} tone="info" className="import-file-icon"/>
        <h3>Drop video or audio here</h3>
        <p className="dropzone-hint">or choose files from your computer</p>
        <button className="primary" disabled={!caps.user.policy.upload||!!working} onClick={()=>fileInput.current?.click()}>Choose files</button><input aria-label="Local media" ref={fileInput} hidden type="file" accept="video/*,audio/*,.mkv,.mov,.webm,.ts" multiple disabled={!caps.user.policy.upload||!!working} onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length)perform('import',()=>upload(files));e.target.value='';}}/>
      </div>
      <dl className="import-limits"><dt>File size limit</dt><dd>{bytes(caps.user.policy.maxInputBytes)} per file</dd><dt>File types</dt><dd>Video and audio</dd></dl>
      {!caps.user.policy.upload&&<p className="permission-note">Import not permitted.</p>}{working==='import'&&<p className="inline-status" role="status">Importing media…</p>}
    </Panel></section><section hidden={method!=='links'}>
      <LinkImport url={urls} setUrl={value=>{setUrls(value);resetInspection();}} canInspect={unique.length===1&&!!caps.user.policy.download} canDownload={unique.length===1&&!!caps.user.policy.download} working={working} error={inspectionError} metadata={metadata} entry={selectedEntry} itemIndex={itemIndex} setItemIndex={setItemIndex} format={format} setFormat={setFormat} inspect={()=>void run(inspectLink)} duration={duration}
        download={(chosen,kind)=>perform('download',async()=>{const item={url:unique[0],preference:kind==='audio'?'audio' as const:preference,itemIndex,...(chosen?{format:chosen}:{}),...(cookieId?{cookieId}:{})};await api.submit({type:'download',download:item});await refresh();done();setNotice('1 download request queued.');})}>
        <details className="settings-block"><summary>Advanced download options</summary><Field label="Authentication"><select value={cookieId} onChange={e=>{setCookieId(e.target.value);resetInspection();}}><option value="">No saved account</option>{cookies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field></details>
      </LinkImport>
    </section></div>
  </div>;
}
export function Library({sources,artifacts,jobs,run,refresh,edit,setNotice,onImport}:{jobs:Job[];onImport:()=>void;sources:Source[];artifacts:Artifact[];run:Task;refresh:()=>Promise<void>;edit:(id:string)=>void;setNotice:(s:string)=>void}) {
  const [status,setStatus]=useState('all');
  const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[preview,setPreview]=useState<string>(),[previewError,setPreviewError]=useState(''),[copyAvailable,setCopyAvailable]=useState(false);
  useEffect(()=>{desktopBridge()?.capabilities().then(c=>setCopyAvailable(c.fileClipboard?.state==='available')).catch(()=>{});},[]);
  const ordered=[...artifacts].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));
  const latest=ordered.find(a=>a.validated&&['export','download'].includes(a.kind));
  const jobName=(job:Job)=>{const sourceId=job.sourceId||(job.request.type==='export'?job.request.recipe.sourceId:job.request.type==='proxy'?job.request.sourceId:undefined);return sources.find(s=>s.id===sourceId)?.name||(job.request.type==='download'?job.request.download.url:job.request.type==='proxy'?'Playback copy':'Video export');};
  const standalone=jobs.filter(j=>j.state!=='completed'||!j.artifactId);
  const rows=[...ordered.map(a=>({id:a.id,name:a.name,createdAt:a.createdAt,artifact:a,job:undefined as Job|undefined})),...standalone.map(j=>({id:j.id,name:jobName(j),createdAt:j.createdAt,artifact:undefined as Artifact|undefined,job:j}))].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));
  const matchesStatus=(row:typeof rows[number],value:string)=>value==='all'||(value==='ready'?!!row.artifact:value==='active'?!!row.job&&!terminalStates.includes(row.job.state):!!row.job&&retryStates.includes(row.job.state));
  const filtered=rows.filter(row=>matchesStatus(row,status)&&row.name.toLowerCase().includes(query.toLowerCase())&&(kind==='all'||(row.artifact?(kind==='sources'?sources.some(s=>s.artifactId===row.id):row.artifact.kind===kind):row.job?.request.type===kind)));
  const selectionItem=(row:typeof rows[number])=>({id:row.id,name:row.name,disabled:row.artifact?row.artifact.pinned:!terminalStates.includes(row.job!.state),original:row.artifact?.kind==='original',history:!!row.job});
  const bulk=useBulkDelete({items:filtered.map(selectionItem),scope:JSON.stringify([query,kind,status]),kind:'items',remove:item=>item.history?api.remove('/jobs/'+item.id):request('/artifacts/'+item.id,{method:'DELETE',body:JSON.stringify({confirmOriginal:item.original})}),refresh,setNotice,beforeOpen:()=>setPreview(undefined)});
  const act=(path:string)=>void run(async()=>{await api.action(path);await refresh();});
  const pending=jobs.filter(j=>j.state==='queued').sort((a,b)=>a.position-b.position);
  const move=(id:string,offset:number)=>void run(async()=>{const ids=pending.map(j=>j.id),i=ids.indexOf(id);if(i<0||i+offset<0||i+offset>=ids.length)return;[ids[i],ids[i+offset]]=[ids[i+offset],ids[i]];await api.action('/jobs/reorder',{ids});await refresh();});
  return <div className="library-page unified-library"><div className="library-surface"><div className="filter-buttons library-status" aria-label="Filter library">{[['all','All'],['ready','Ready'],['active','In progress'],['attention','Needs attention']].map(([value,label])=><button key={value} aria-pressed={status===value} onClick={()=>{bulk.clear();setStatus(value);}}>{label} <span>{rows.filter(row=>matchesStatus(row,value)).length}</span></button>)}</div><div className="library-tools"><Field label="Search media"><input className="search-input" type="search" placeholder="Search videos or links" value={query} onChange={e=>{bulk.clear();setQuery(e.target.value);}}/></Field><Field label="Show media"><select value={kind} onChange={e=>{bulk.clear();setKind(e.target.value);}}><option value="all">All media</option><option value="sources">Sources</option><option value="export">Exports</option><option value="download">Downloads</option><option value="proxy">Playback previews</option></select></Field><span className="library-count">{filtered.length} {filtered.length===1?'item':'items'}</span>{desktopBridge()&&<button disabled={!latest||!copyAvailable} onClick={()=>void run(async()=>{if(!latest)return;await desktopBridge()!.copyFile(latest.id);setNotice(`Copied: ${latest.name}`);})}>Copy latest output file</button>}</div>
    {bulk.controls}
    {!filtered.length&&<div className="library-empty"><EmptyState icon={rows.length?'search':'library'} title={rows.length?'No matching media':'Your library starts here'}/>{!rows.length&&<><p>Import files from your computer or download a video from a link.</p><button className="primary" onClick={onImport}>Import</button></>}</div>}
    {!!filtered.length&&<p className="library-sort-note">Newest first</p>}
    <div className="library media-list">{filtered.map(row=>{if(row.job){const j=row.job,finished=terminalStates.includes(j.state);return <article className="media-card activity-card" key={j.id} data-job-id={j.id}>
      <div className="media-card-heading"><div className="activity-mark"><EditorIcon name={j.request.type==='download'?'download':'video'} size={28}/><span>{j.request.type==='download'?'Download':j.request.type==='proxy'?'Playback copy':'Export'}</span></div><div className="media-name"><div className="selection-title">{bulk.checkbox(selectionItem(row))}<h3>{row.name}</h3></div><span className={`job-state job-state-${j.state}`} data-tone={stateTones[j.state]||'muted'}>{statusNames[j.state]}</span><JobProgress job={j} name={row.name}/>{j.error&&<p className="activity-error">{j.error}</p>}{j.message&&!j.error&&<small>{j.message}</small>}<details className="activity-details"><summary>Activity details</summary><p>{dateTime(j.createdAt)} | Attempt {j.attempt}</p>{j.state==='queued'&&<div className="actions"><button disabled={pending[0]?.id===j.id} onClick={()=>move(j.id,-1)}>Move up</button><button disabled={pending.at(-1)?.id===j.id} onClick={()=>move(j.id,1)}>Move down</button></div>}{j.plan&&<pre>{JSON.stringify(j.plan,null,2)}</pre>}</details></div><div className="actions media-primary-actions">{!finished&&<button disabled={j.state==='cancelling'} onClick={()=>act(`/jobs/${j.id}/cancel`)}>Cancel</button>}{retryStates.includes(j.state)&&<button className="primary" onClick={()=>act(`/jobs/${j.id}/retry`)}>Retry</button>}{finished&&<button className="danger-quiet" onClick={()=>bulk.open([selectionItem(row)])}>Delete</button>}</div></div>

    </article>;}const a=row.artifact!;const source=sources.find(s=>s.artifactId===a.id),video=a.media.streams.find(s=>s.type==='video'),audioOnly=!video&&a.media.streams.some(s=>s.type==='audio');return <article className="media-card" key={a.id} data-artifact-id={a.id}>
      <div className="media-card-heading">{video?<LibraryThumbnail id={a.id} name={a.name} duration={duration(a.media.duration)} onPreview={()=>{setPreview(preview===a.id?undefined:a.id);setPreviewError('');}}/>:<div className="media-file-mark" aria-hidden="true"><EditorIcon name="audio" size={26} tone="audio"/></div>}<div className="media-name"><div className="selection-title">{bulk.checkbox({id:a.id,name:a.name,disabled:a.pinned})}<h3>{a.name}</h3></div><div className="media-facts"><span className="ready-label">Ready</span><span className={`media-kind media-kind-${a.kind}`}>{mediaKinds[a.kind]}</span><span>{duration(a.media.duration)}</span><span>{bytes(a.bytes)}</span>{video?.width&&video.height&&<span>{video.width} × {video.height}</span>}{a.pinned&&<span className="protected-label">Protected</span>}</div></div><div className="actions media-primary-actions"><button aria-expanded={preview===a.id} onClick={()=>{setPreview(preview===a.id?undefined:a.id);setPreviewError('');}}><EditorIcon name={preview===a.id?'close':'eye'} size={16}/>{preview===a.id?'Close preview':'Preview'}</button><button className="primary" aria-label={source?'Edit source':'Edit clip'} onClick={()=>void run(async()=>{const editable=source||await api.editArtifact(a.id);await refresh();edit(editable.id);})}><EditorIcon name="edit" size={16}/>Edit</button><button className="library-delete-button danger-quiet" aria-label={`Delete ${a.name}`} disabled={a.pinned} title={a.pinned?"Pinned media is protected from deletion.":"Delete from library"} onClick={()=>bulk.open([selectionItem(row)])}><EditorIcon name="trash" size={16}/>Delete</button></div></div>
      {preview===a.id&&<div className="library-preview">{audioOnly?<audio controls src={contentUrl(a.id)} preload="metadata" onError={()=>setPreviewError(a.id)}/>:<video controls src={contentUrl(a.id)} preload="metadata" onError={()=>setPreviewError(a.id)}/>}{previewError===a.id&&<p className="permission-note">Cannot play this format. Create a playback copy in the editor.</p>}</div>}
      <div className="media-card-actions"><ArtifactActions artifact={a} run={run} setNotice={setNotice}/><details className="media-manage"><summary>File details</summary><dl className="file-details"><dt>Added</dt><dd>{dateTime(a.createdAt)}</dd><dt>File check</dt><dd>{a.validated?'Passed':'Not checked'}</dd><dt>Storage</dt><dd>{a.pinned?'Protected from deletion':'Managed copy'}</dd></dl><details><summary>Technical metadata</summary><pre>{JSON.stringify(a.media,null,2)}</pre></details>{jobs.filter(j=>j.state==='completed'&&j.artifactId===a.id).map(j=><div className="completed-activity" key={j.id}><strong>{j.request.type==='download'?'Download':j.request.type==='proxy'?'Playback copy':'Export'} completed</strong><p>{dateTime(j.updatedAt)} | Attempt {j.attempt}</p><button onClick={()=>bulk.open([{id:j.id,name:a.name,history:true}])}>Delete history only</button>{j.plan&&<details><summary>Processing details</summary><pre>{JSON.stringify(j.plan,null,2)}</pre></details>}</div>)}</details></div>
    </article>;})}</div>
    {!!jobs.length&&<details className="library-history"><summary>Activity history</summary><p>Completed activity is included in file details. History remains available after a file is removed.</p><div className="actions"><button onClick={()=>saveJson('media-results.json',jobs)}>Save history JSON</button><a href="/api/v1/history/export?format=csv" download="media-results.csv">Save history CSV</a></div>{[...new Set(jobs.map(j=>j.batchId).filter(Boolean))].map(id=><div className="actions" key={id}><span>Batch {id!.slice(0,8)}</span><button disabled={!jobs.some(j=>j.batchId===id&&!terminalStates.includes(j.state))} onClick={()=>act(`/batches/${id}/cancel`)}>Cancel batch</button><button disabled={!jobs.some(j=>j.batchId===id&&retryStates.includes(j.state))} onClick={()=>act(`/batches/${id}/retry`)}>Retry failed</button></div>)}</details>}
  </div></div>;
}

export function SavedProjects({run,onProject}:{run:Task;onProject:(p:Project)=>void}) {
  const [projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true);
  const load=async()=>{try{setProjects(await api.projects());}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="projects-page"><Panel title="Saved projects">{loading?<p className="inline-status" role="status">Loading projects…</p>:!projects.length&&<EmptyState icon="save" title="No saved projects"/>}<div className="project-list">{projects.map(p=><article className="row project-row" key={p.id}><div className="project-name"><strong>{p.name}</strong><small>Updated {dateTime(p.updatedAt)}</small></div><div className="actions"><button onClick={()=>onProject(p)}><EditorIcon name="folder" size={16}/>Load project</button><details className="project-manage"><summary>More</summary><button className="quiet" onClick={()=>void run(async()=>{await api.remove(`/projects/${p.id}`);await load();})}>Delete project recipe</button></details></div></article>)}</div></Panel></div>;
}

export function Presets({run}:{run:Task;onProject:(p:Project)=>void}) {
  const [presets,setPresets]=useState<any[]>([]),[payload,setPayload]=useState(''),[validation,setValidation]=useState<any>(),[loading,setLoading]=useState(true);
  const load=async()=>{try{setPresets(await request<any[]>('/presets'));}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="columns settings-columns presets-page"><Panel title="Export presets">{loading?<p className="inline-status" role="status">Loading presets…</p>:!presets.length&&<EmptyState title="No saved presets"/>}{presets.map(item=><article key={item.id||item.preset?.id} className="row preset-row"><strong>{item.name||item.preset?.name}</strong><button onClick={()=>void run(async()=>saveJson('media-preset.json',await request(`/presets/${item.id}`)))}>Export JSON</button></article>)}</Panel>
    <Panel title="Import or create a preset"><Field label="Open preset JSON"><input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{setPayload(await f.text());setValidation(undefined);});e.target.value='';}}/></Field><div className="actions"><button onClick={()=>{setPayload(JSON.stringify({schemaVersion:1,id:'my-sharing-preset',revision:1,name:'My sharing preset',requires:['exact-cut-v1','target-size-v1'],options:ExportSchema.parse({cut:'exact',mode:'size',maxBytes:20_000_000})},null,2));setValidation(undefined);}}>New editable preset</button></div><Field label="Preset JSON"><textarea className="json-input" rows={12} value={payload} spellCheck={false} onChange={e=>{setPayload(e.target.value);setValidation(undefined);}}/></Field><div className="actions"><button disabled={!payload.trim()} onClick={()=>void run(async()=>setValidation(await api.action('/presets/validate',JSON.parse(payload))))}>Validate preset</button><button className="primary" disabled={!validation} onClick={()=>void run(async()=>{await api.action('/presets/import',JSON.parse(payload));await load();})}>Import validated preset</button></div>{validation&&<div className="preset-validation"><h3>Validation result</h3><pre>{JSON.stringify(validation,null,2)}</pre></div>}</Panel>
  </div>;
}
const nativeLabels:Record<string,string>={fileClipboard:'Copy files',pathClipboard:'Copy paths',revealFile:'Show file location',saveAs:'Save a copy',nativeDragOut:'Drag files to another app',externalActions:'Open in other apps'};
export function Integrations({caps,run,setNotice}:{caps:Capabilities;run:Task;setNotice:(s:string)=>void}) {
  const bridge=desktopBridge(),[native,setNative]=useState<Record<string,{state:string;reason?:string}>>(browserCapabilities),[actions,setActions]=useState<any[]>([]),[cookies,setCookies]=useState<any[]>([]),[loading,setLoading]=useState(true);
  const [name,setName]=useState('Open in editor'),[args,setArgs]=useState('["{file}"]'),[uploads,setUploads]=useState(false),[timeoutSeconds,setTimeoutSeconds]=useState(30),[browser,setBrowser]=useState('chrome'),[profile,setProfile]=useState(''),[shareXTask,setShareXTask]=useState('');
  const load=async()=>{try{if(bridge){setNative(await bridge.capabilities());setActions(await bridge.listActions());}if(caps.mode==='local'&&caps.user.role==='owner')setCookies(await request('/cookies'));}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="columns settings-columns integrations-page"><Panel title="Desktop integrations"><div className="capability-list">{Object.entries(native).map(([key,v])=><div className="capability-row" key={key}><strong>{nativeLabels[key]||key}</strong><span className="capability-state">{v.state==='available'?'Available':v.state==='permission-denied'?'Permission needed':'Unavailable'}</span>{v.reason&&<small>{v.reason}</small>}</div>)}</div>
    {bridge?<details className="settings-block"><summary>Open files in another app</summary>{actions.map(a=><div className="row" key={a.id}><strong>{a.name}</strong><span>{a.uploads?'Uploads files':'Local app'} · {a.timeoutSeconds} second limit</span></div>)}<Field label="Action name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Argument array JSON" help="Placeholders: {file}, {filename}, {directory}."><textarea className="json-input" value={args} onChange={e=>setArgs(e.target.value)} spellCheck={false}/></Field><NumberField label="Action timeout (seconds)" value={timeoutSeconds} min={1} max={300} step={1} onChange={setTimeoutSeconds}/><Checkbox label="This action uploads media to another service" value={uploads} onChange={setUploads}/><button disabled={!name.trim()} onClick={()=>void run(async()=>{await bridge.configureAction({name,args:JSON.parse(args),uploads,timeoutSeconds});await load();setNotice('App setup closed.');})}>Choose executable and save binding</button><details className="settings-block"><summary>ShareX setup</summary><Field label="Configured ShareX task name"><input value={shareXTask} onChange={e=>setShareXTask(e.target.value)}/></Field><button disabled={!shareXTask.trim()} onClick={()=>void run(async()=>{await bridge.configureAction(shareXAction(shareXTask));await load();setNotice('ShareX setup closed.');})}>Choose ShareX.exe and register task</button></details></details>:<p className="permission-note">Desktop app required.</p>}
    </Panel><Panel title="Download accounts">{caps.mode==='local'&&caps.user.role==='owner'?<><p className="permission-note">Cookies grant account access. Keep them private.</p>{loading&&<p className="inline-status" role="status">Loading saved accounts…</p>}{!loading&&!cookies.length&&<p className="page-note">No saved accounts.</p>}{cookies.map(c=><div className="row credential-row" key={c.id}><span>{c.name}{c.browser?` (${c.browser})`:''}</span><button onClick={()=>void run(async()=>{await api.remove(`/cookies/${c.id}`);await load();})}>Forget credential</button></div>)}<Field label="Netscape cookies file"><input type="file" accept=".txt" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{await api.action('/cookies/import',{name:file.name,content:await file.text()});await load();setNotice('Account imported.');});e.target.value='';}}/></Field><details className="settings-block"><summary>Use a local browser account</summary><div className="form-grid"><Field label="Local browser"><select value={browser} onChange={e=>setBrowser(e.target.value)}>{['chrome','edge','firefox','chromium','brave','opera','vivaldi'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Profile name (optional)"><input value={profile} onChange={e=>setProfile(e.target.value)}/></Field></div><button onClick={()=>void run(async()=>{await api.action('/cookies/browser',{browser,...(profile?{profile}:{})});await load();setNotice('Browser account added.');})}>Use this local browser profile</button></details></>:<p className="permission-note">Local owner access required.</p>}</Panel>
  </div>;
}
export function Settings({caps,run,setNotice}:{caps:Capabilities;run:Task;setNotice:(s:string)=>void}) {
  const [concurrency,setConcurrency]=useState(1),[maxConcurrency,setMaxConcurrency]=useState(caps.user.policy.concurrency),[diagnostics,setDiagnostics]=useState<any>(),[loading,setLoading]=useState(true);
  useEffect(()=>{void run(async()=>{try{const v=await request<any>('/settings');setConcurrency(v.concurrency);setMaxConcurrency(v.maxConcurrency);}finally{setLoading(false);}});},[]);
  return <div className="columns settings-columns general-settings"><Panel title="Processing"><NumberField label="Maximum concurrent jobs" value={concurrency} min={1} max={maxConcurrency} step={1} disabled={caps.user.role!=='owner'||loading} onChange={setConcurrency}/><button className="primary" disabled={caps.user.role!=='owner'||loading} onClick={()=>void run(async()=>{const result=await api.patch('/settings',{concurrency});setConcurrency(result.concurrency);setNotice('Concurrency setting saved.');})}>Save concurrency</button>{caps.user.role!=='owner'&&<p className="permission-note">Owner access required.</p>}<details className="settings-block"><summary>Account permissions and limits</summary><dl className="permission-list"><dt>Import files</dt><dd>{caps.user.policy.upload?'Allowed':'Unavailable'}</dd><dt>Download links</dt><dd>{caps.user.policy.download?'Allowed':'Unavailable'}</dd><dt>Edit and export</dt><dd>{caps.user.policy.process?'Allowed':'Unavailable'}</dd><dt>Input size</dt><dd>{bytes(caps.user.policy.maxInputBytes)}</dd><dt>Output size</dt><dd>{bytes(caps.user.policy.maxOutputBytes)}</dd></dl><details><summary>Full permission details</summary><pre>{JSON.stringify(caps.user.policy,null,2)}</pre></details></details></Panel>
    <Panel title="Tools and support"><dl className="tools-list">{Object.entries(caps.tools).map(([name,v])=><React.Fragment key={name}><dt>{name}</dt><dd>{v}</dd></React.Fragment>)}</dl><details className="settings-block"><summary>Available video encoders</summary><div className="table-scroll"><table className="encoders-table"><thead><tr><th>Encoder</th><th>Processing</th><th>Status</th></tr></thead><tbody>{caps.encoders.map(e=><tr key={e.name}><td data-label="Encoder">{e.name}<small>{e.codec}</small></td><td data-label="Processing">{e.hardware?'Graphics card':'Processor'}</td><td data-label="Status">{e.available?'Available':'Unavailable'}{e.reason&&<small>{e.reason}</small>}<small>Checked {dateTime(e.testedAt)}</small></td></tr>)}</tbody></table></div></details><button onClick={()=>void run(async()=>setDiagnostics(await request('/diagnostics')))}>Prepare support data</button>{diagnostics&&<div className="support-data"><h3>Review before saving</h3><pre>{JSON.stringify(diagnostics,null,2)}</pre><button onClick={()=>saveJson('media-workbench-diagnostics.json',diagnostics)}>Save reviewed support data</button></div>}</Panel>
  </div>;
}

export function Administration({run,setNotice}:{run:Task;setNotice:(s:string)=>void}) {
  const [users,setUsers]=useState<any[]>([]),[pairings,setPairings]=useState<any[]>([]),[loading,setLoading]=useState(true),[name,setName]=useState(''),[role,setRole]=useState('restricted-guest'),[credential,setCredential]=useState(''),[pairName,setPairName]=useState('Browser client'),[policy,setPolicy]=useState(''),[userId,setUserId]=useState('');
  const load=async()=>{try{const [u,p]=await Promise.all([request<any[]>('/admin/users'),request<any[]>('/pairings')]);setUsers(u);setPairings(p);}finally{setLoading(false);}};
  useEffect(()=>{void run(load);},[]);
  return <div className="administration-page">{credential&&<div className="notice credential-notice"><h3>Save this access token now</h3><p>It is shown only once. Keep it private.</p><code className="secret">{credential}</code><button onClick={()=>setCredential('')}>Hide credential</button></div>}<div className="columns settings-columns"><Panel title="Users"><div className="form-grid"><Field label="New user name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="New user role"><select value={role} onChange={e=>setRole(e.target.value)}><option value="restricted-guest">Guest — download only</option><option value="member">Member — edit and export</option></select></Field></div><button className="primary" disabled={!name.trim()} onClick={()=>void run(async()=>{const result=await api.action('/admin/users',{name,role});setCredential(result.token||result.credential||'');await load();})}>Create user</button>
    {loading?<p className="inline-status" role="status">Loading users…</p>:<div className="table-scroll"><table className="users-table"><thead><tr><th>Name</th><th>Role</th><th>Limits</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td data-label="Name">{u.name}</td><td data-label="Role">{u.role==='owner'?'Owner':u.role==='member'?'Member':'Guest'}</td><td data-label="Limits"><button onClick={()=>{setUserId(u.id);setPolicy(JSON.stringify(u.policy,null,2));}}>Edit limits</button></td></tr>)}</tbody></table></div>}{userId&&<div className="policy-editor"><h3>Limits for {users.find(u=>u.id===userId)?.name||'selected user'}</h3><Field label="Selected user policy JSON"><textarea className="json-input" rows={12} value={policy} onChange={e=>setPolicy(e.target.value)} spellCheck={false}/></Field><div className="actions"><button className="primary" onClick={()=>void run(async()=>{await api.patch(`/admin/users/${userId}`,{policy:JSON.parse(policy)});await load();setNotice('Limits saved.');})}>Save selected user policy</button><button onClick={()=>{setUserId('');setPolicy('');}}>Close limits</button></div></div>}
    </Panel><Panel title="Connected clients"><Field label="Client name"><input value={pairName} onChange={e=>setPairName(e.target.value)}/></Field><button disabled={!pairName.trim()} onClick={()=>void run(async()=>{const result=await api.action('/pairings',{name:pairName,scopes:['read','submit']});setCredential(result.token||result.credential||'');await load();})}>Create scoped pairing</button><p className="permission-note">Keep access tokens private.</p>{!loading&&!pairings.length&&<p className="page-note">No connected clients.</p>}{pairings.map(p=><div className="row pairing-row" key={p.id}><div><strong>{p.name}</strong><small>{(p.scopes||[]).join(', ')}</small></div><button onClick={()=>void run(async()=>{await api.remove(`/pairings/${p.id}`);await load();})}>Revoke pairing</button></div>)}<details className="settings-block"><summary>Storage cleanup</summary><button onClick={()=>void run(async()=>{const result=await api.action('/retention');setNotice(`Cleanup: ${JSON.stringify(result)}`);})}>Run managed retention cleanup</button></details></Panel></div>
  </div>;
}
